{
 "title": "EduLMS SRE — Overview",
 "tags": [
  "edulms",
  "sre"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate (req/s) — payment",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (status) (rate(payment_requests_total[1m]))",
     "legendFormat": "status={{status}}"
    }
   ]
  },
  {
   "title": "Error rate (%) — payment",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(payment_requests_total{status=~\"5..\"}[5m])) / clamp_min(sum(rate(payment_requests_total[5m])),0.001)",
     "legendFormat": "5xx %"
    }
   ]
  },
  {
   "title": "Latency p95 (s) — payment",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(payment_request_latency_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(payment_request_latency_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Profiles count",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "user_profile_count" }
   ]
  },
  {
   "title": "In-flight (payment)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "payment_inflight_requests" }
   ]
  },
  {
   "title": "Up status — every service",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 4 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} / {{instance}}" }
   ]
  }
 ]
}